### ISSUE TITLE
d1的表结构

### ISSUE THREAD

**Issue by sidneycao** [emaction/emaction.backend#1]
能提供下d1的表结构吗？ work.js中似乎没有初始化表的语句

**Comment by lmm214** [comment]
同问

**Comment by eallion** [comment]
+1

**Comment by eallion** [comment]
```
wrangler d1 execute emaction --command='CREATE TABLE reactions (id INTEGER PRIMARY KEY AUTOINCREMENT, target_id TEXT NOT NULL, reaction_name TEXT NOT NULL, count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)'
```
用这个 `wrangler` 命令可创建，数据表是通过 worker.js 逆向反推的。

**Comment by sidneycao** [comment]
> ```
> wrangler d1 execute emaction --command='CREATE TABLE reactions (id INTEGER PRIMARY KEY AUTOINCREMENT, target_id TEXT NOT NULL, reaction_name TEXT NOT NULL, count INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)'
> ```
> 
> 用这个 `wrangler` 命令可创建，数据表是通过 worker.js 逆向反推的。

亲测可用 老哥给力
